/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.2.2] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <windows.h>
#include "C:\BUSMASTER_v3.2.2\SimulatedSystems\include\CANIncludes.h"
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
STCAN_MSG tx;
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnMsgID_123(STCAN_MSG RxMsg);
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
/* End BUSMASTER Function Wrapper Prototype  */


/* Start BUSMASTER generated function - OnMsgID_123 */
void OnMsgID_123(STCAN_MSG RxMsg)
{
/* TODO */
tx.id = 0x123;
tx.dlc = 8;
tx.data[0] = 12;
tx.data[1] = 13;
tx.data[2] = 14;
tx.data[3] = 15;
tx.data[4] = 16;
tx.data[5] = 17;
tx.data[6] = 18;
tx.data[7] = 19;
SendMsg(tx);
}/* End BUSMASTER generated function - OnMsgID_123 */
